name: 📦 Package NuGet and Create Release

on:
  workflow_dispatch: # Manual trigger from GitHub UI
jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Build
        run: dotnet build --configuration Release

      - name: Pack NuGet packages
        run: |
          for proj in ./ADFNet.*/*.csproj; do
            dotnet pack "$proj" \
              --no-build \
              --configuration Release \
              --output ./nupkg
          done

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --title "${GITHUB_REF_NAME}" \
            --notes "Automated release for ${GITHUB_REF_NAME}" \
            nupkg/*.nupkg

      - name: Push packages to NuGet
        run: |
          for pkg in nupkg/**/*.nupkg; do
            if [[ "$pkg" != *.symbols.nupkg ]]; then
              echo "Pushing $pkg..."
              dotnet nuget push "$pkg" \
                --api-key "${{ secrets.NUGET_API_KEY }}" \
                --source https://api.nuget.org/v3/index.json
            fi
          done

