name: 🚀 GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'preview-v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ./nupkg

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --title "${GITHUB_REF_NAME}" \
            --notes "Automated release for ${GITHUB_REF_NAME}" \
            nupkg/*.nupkg
